repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Note: mypy is INTENTIONALLY skipped in pre-commit due to heavy dependencies
  # Run mypy manually with: uv run mypy src/ --strict
  # OR run ./scripts/validate.sh before pushing (includes mypy check)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: detect-unused-tables
        name: Detect unused database tables
        entry: python3 scripts/detect_unused_tables.py
        language: system
        files: ^src/geistfabrik/(schema\.py|.*\.py)$
        pass_filenames: false
